objects/Child__c.object
<CustomObject>
    <fields>
        <fullName>Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent</label>
        <referenceTo>Parent__c</referenceTo>
        <relationshipLabel>Children</relationshipLabel>
        <relationshipName>Children</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Child</label>
    <nameField>
        <label>Child Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Children</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Grandchild__c.object
<CustomObject>
    <fields>
        <fullName>Child__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Child</label>
        <referenceTo>Child__c</referenceTo>
        <relationshipLabel>Grandchildren</relationshipLabel>
        <relationshipName>Grandchildren</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Grandchild</label>
    <nameField>
        <label>Grandchild Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grandchildren</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Parent__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Parent</label>
    <nameField>
        <label>Parent Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Parentchildgchandler.cls
public class Parentchildgchandler {
    public void updatesubinc(List<Parent__c> plist){
        List<id> pid = new List<id>();
        for(Parent__c par:plist){
            if(par.Status__c=='In Progress'){
                pid.add(par.id);
            }
            List<Child__c> clist = [Select id,Subject__c, Parent__r.Subject__c, Parent__r.Status__c from Child__c where Parent__c =:plist];
            
            List<Child__c> childlist = new List<Child__c>();
            Child__c cr = new Child__c();
            for(Child__c crec:clist){
                if(crec.Parent__r.Status__c == 'In Progress'){
                    cr = new Child__c();
                    cr.id = crec.id;
                    cr.Subject__c = crec.Parent__r.Subject__c;
                    childlist.add(cr);
                }
                
                update childlist;	
                        
            Set<String> gchild = new Set<String>();
            for(Child__c chi:clist){
                gchild.add(chi.id);
            }
            
            List<Grandchild__c> grandchildlist = new List<Grandchild__c>();
            List<Grandchild__c> glist = [Select id,Subject__c,Child__r.Subject__c from Grandchild__c where Child__c in:gchild];
            Grandchild__c grecord = New Grandchild__c();
            
            
                for(Grandchild__c grec:glist){
                    if(crec.id == grec.Child__c){
                        grecord = new Grandchild__c();
                        grecord.id=grec.id;
                        grecord.Subject__c = crec.Parent__r.Subject__c;
                        grandchildlist.add(grecord);
                    }
                    update grandchildlist;
                }
            }
        }
    }
}